### ISSUE TITLE
constructor JSCJavaScriptExecutorFactory in class JSCJavaScriptExecutorFactory cannot be applied to given types

### ISSUE THREAD

**Issue by Unforgiven-wanda** [Traviskn/react-native-threads#11]
Hello,
Using this lib with the latest stable RN version 0.51.0 I have encoutered the following issue when trying to run an Android project
```
myproject/node_modules/react-native-threads/android/src/main/java/com/reactlibrary/ReactContextBuilder.java:57: error: constructor JSCJavaScriptExecutorFactory in class JSCJavaScriptExecutorFactory cannot be applied to given types;
        JavaScriptExecutor jsExecutor = new JSCJavaScriptExecutorFactory().create();
                                        ^
  required: String,String
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:react-native-threads:compileReleaseJavaWithJavac FAILED
```
I have scoured the list of breaking changes since 0.49 but haven't managed to pinpoint the culprit.
I also haven't had the chance to try this on an IOS device.
Could I  trouble you for a quick fix?

Thank you very much.

**Comment by Traviskn** [comment]
@Unforgiven-wanda Yes I run into this error too using the latest version.  Unfortunately the internal android API's this library uses change with nearly each release.  It looks like there's a PR by @newyankeecodeshop that could fix it though, I'll take a look at that and see if it helps!
