### ISSUE TITLE
I don't think it works on 0.63 iOS

### ISSUE THREAD

**Issue by backmeupplz** [Traviskn/react-native-threads#123]
Hey there! Anyone got it working on iOS? It seems like when `RCTBridge` for the main React Native app is instantiated, the new RCTBridges don't start the JS code 🤔

**Comment by backmeupplz** [comment]
Actually, tried it out and the approach taken by this library should be working on the latest React Native version (0.63.4): https://github.com/backmeupplz/react-native-ios-threading-example/

**Comment by backmeupplz** [comment]
Looks like Realm can be the issue, investigating there: https://github.com/realm/realm-js/issues/3522

**Comment by jacobp100** [comment]
It works on 0.63
