### ISSUE TITLE
iOS bundle won't load

### ISSUE THREAD

**Issue by jliebrand** [Traviskn/react-native-threads#6]
I have everything working as long as the package manager is running. But as soon as I try to build for production, or indeed even just bundle the thread with --dev true, it fails to load the bundled thread code.

Looking through the logs, I noticed this:
starting Thread file:///var/containers/Bundle/Application/0C3714D5-035B-480F-A9A7-4D2455ECF6BA/MyApp.app/main.jsbundle

My thread entry point is navigator.js (and output as well)... Which would imply that the fallback incorrectly falls back to the name "main" causing it to load the wrong JS bundle?

**Comment by jliebrand** [comment]
sorry I should have noted this is running on my iPad

**Comment by jliebrand** [comment]
ps. I also verified that log message does indeed come from the ThreadManager.m:24

**Comment by jliebrand** [comment]
Think I found the problem... In RCTBundleURLProvider.m:

```
- (NSURL *)jsBundleURLForBundleRoot:(NSString *)bundleRoot fallbackResource:(NSString *)resourceName
{
  resourceName = resourceName ?: @"main";
  NSString *packagerServerHost = [self packagerServerHost];
  if (!packagerServerHost) {
    return [[NSBundle mainBundle] URLForResource:resourceName withExtension:@"jsbundle"];
  } else {
    NSString *path = [NSString stringWithFormat:@"/%@.bundle", bundleRoot];
    // When we support only iOS 8 and above, use queryItems for a better API.
    NSString *query = [NSString stringWithFormat:@"platform=ios&dev=%@&minify=%@",
                       [self enableDev] ? @"true" : @"false",
                       [self enableMinification] ? @"true": @"false"];
    return [[self class] resourceURLForResourcePath:path packagerHost:packagerServerHost query:query];
  }
}
```

That bit of code will default to 'main.jsbundle' if there is no packagerServerHost.  Not sure how this would ever work for release/production for the thread bundle?

(this is running "react-native": "0.49.1")

**Comment by jliebrand** [comment]
oh wait... it just means the ThreadManager needs to pass the thread name along as the fallbackResource? Let me try that

**Comment by jliebrand** [comment]
Ok getting somewhere..
1- needed to change the production script to --bundle-output ./ios/navigator.jsbundle
2- needed to edit the ThreadManager to pass the name of the thread to the fallbackResource

That now at least tries to load the correct bundle!

(but it now crashes with EXC_BAD_ACCESS on RCTImageLoader - no idea if that is related or not)

**Comment by jliebrand** [comment]
That exception appears to be a red herring... refreshing did the trick.

I'll see if I can put together a PR for the ThreadManager

**Comment by Traviskn** [comment]
@jliebrand Thanks for figuring all this out!  You're right, the wrong file gets loaded in release mode 🙈 I'll go over your PR's now

**Comment by Traviskn** [comment]
fixes are merged!  thanks again for the help

**Comment by jliebrand** [comment]
NP
